<a href="https://colab.research.google.com/github/voknerog/pandas_numpy_matplotlib/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 1. Import the numpy package under the name np (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
print(np.__version__)

1.23.5


#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
n = 10
a_3 = np.zeros(n)

#### 4. How to find the memory size of any array (★☆☆)

In [5]:
res_3 = a_3.nbytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [6]:
res_5 = [np.info(np.add), np.info(np.array)]

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
n = 10
a_6 = np.zeros(n)
a_6[4] = 1

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [8]:
n = 10
m = 49
a_7 = np.arange(n, m+1)


#### 8. Reverse a vector (first element becomes last) (★☆☆)


In [9]:
a_8 = a_7[::-1]

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
a_9 = np.arange(9)
a_9 = np.reshape(a_9, (3, 3))
a_9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [11]:
a_10 = [1,2,0,0,4,0]
res_10 = np.nonzero(a_10)
res_10[0]


array([0, 1, 4])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [12]:
a_11 = np.identity(3)
a_11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [13]:
a_12 = np.random.random((3,3,3))
a_12

array([[[0.62994116, 0.81584594, 0.51968   ],
        [0.5997803 , 0.51990331, 0.27311286],
        [0.54997278, 0.16633567, 0.85691833]],

       [[0.58822726, 0.49153568, 0.07707001],
        [0.29443358, 0.87838749, 0.6128359 ],
        [0.68257996, 0.90396623, 0.63900794]],

       [[0.78044709, 0.16677398, 0.0129348 ],
        [0.75118618, 0.26598265, 0.6907092 ],
        [0.90880822, 0.20213594, 0.83972172]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
a_13 = np.random.random((10,10))
f'min: {np.min(a_13)}, max: {np.max(a_13)}'

'min: 0.0024547488700147335, max: 0.9925434972776471'

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
a_14 = np.random.random(14)
a_14.mean()

0.5217409998713362

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
a_15 = np.zeros((10,10))
a_15[0] = 1
a_15[-1] = 1
a_15[:, 0] = 1
a_15[:, -1] = 1
a_15

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
a_16 = np.pad(a_15,(1,1), mode='constant')
a_16

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆)<br>
0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
 0.3 == 3 * 0.1<br>

In [18]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [19]:
a_18 = np.diagflat([1, 2, 3, 4], -1)
a_18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [20]:
a_19 = np.ones((8, 8))
a_19[::2, ::2] = 0
a_19[1::2,1::2] = 0
a_19

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [21]:
a_20 = np.array((6,7,8))
res_20 = np.unravel_index(100, (6, 7, 8))
res_20

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)


In [22]:
a_21 = np.tile([[0, 1],[1, 0]], (4, 4))
a_21

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆)


In [23]:
a_22 = np.random.random((5, 5))
res_22 = np.around((a_22 - np.mean(a_22)) / np.std(a_22), decimals=2)
res_22

array([[ 1.11,  0.89, -1.45, -0.95,  0.14],
       [ 1.22, -0.86, -1.11, -0.67,  0.93],
       [-0.55, -1.27, -0.57,  1.19,  0.97],
       [-0.83,  0.3 , -0.49,  1.06, -1.41],
       [ 1.1 ,  1.3 ,  0.73, -1.55,  0.78]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
a_23 = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])
a_23

<ipython-input-24-62d52dc41ca1>:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a_23 = np.dtype([("r", np.ubyte, 1), ("g", np.ubyte, 1), ("b", np.ubyte, 1), ("a", np.ubyte, 1)])


dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)


In [25]:
A = np.random.random((5, 3))
B = np.random.random((3, 2))
a_24 = np.dot(A, B)
a_24

array([[0.70701216, 1.37014277],
       [0.50196488, 0.63662914],
       [0.5841159 , 1.08072384],
       [0.57746729, 1.04821763],
       [0.70445388, 1.07883756]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)


In [26]:
a_25 = np.random.random((10)) * 10
a_25 = np.where((a_25 > 7) | (a_25 < 4), a_25, a_25 * -1)
a_25

array([-6.93755503,  2.38068643,  9.187301  , -5.90368108, -6.19847887,
        7.65701961,  1.56802376,  3.44848726, -6.68929504,  1.96118877])

#### 26. What is the output of the following script? (★☆☆)


In [27]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
* Z**Z
* 2 << Z >> 2
* Z <- Z
* 1j*Z
* Z/1/1
* Z<Z>Z

#### 28. What are the result of the following expressions?

* print(np.array(0) / np.array(0))
* print(np.array(0) // np.array(0))
* print(np.array([np.nan]).astype(int).astype(float))

#### 29. How to round away from zero a float array ? (★☆☆)

In [28]:
a_29 = a_25
a_29 = np.where(a_29 > 0, a_29, np.floor(a_29))
a_29 = np.where(a_29 < 0, a_29, np.ceil(a_29))
a_29

array([-7.,  3., 10., -6., -7.,  8.,  2.,  4., -7.,  2.])

#### 30. How to find common values between two arrays? (★☆☆)

In [29]:
a_30 = np.intersect1d(a_29, a_25)
a_30

array([], dtype=float64)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)


In [30]:
# np.seterr(all='ignore')

#### 32. Is the following expressions true? (★☆☆)

In [31]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-31-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

####  33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [32]:
print(np.datetime64('today'))
print(np.datetime64('today') - 1)
print(np.datetime64('today') + 1)


2023-10-02
2023-10-01
2023-10-03


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [33]:
a_34 = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
a_34

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [34]:
A = np.random.random((10)) * 9
B = np.random.random((10)) * 10
np.add(A, B, out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-39.02785532, -44.84790439, -59.91529233, -37.45348609,
       -14.93658729, -17.55382151, -16.69107186, -30.78506023,
        -8.29274122,  -3.31858824])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)


In [35]:
Z = np.random.uniform(0,10,10)
print(np.floor(Z))
print(np.ceil(Z)-1)
print(np.trunc(Z))
print(Z.astype(int))

[8. 2. 6. 6. 6. 7. 9. 9. 5. 7.]
[8. 2. 6. 6. 6. 7. 9. 9. 5. 7.]
[8. 2. 6. 6. 6. 7. 9. 9. 5. 7.]
[8 2 6 6 6 7 9 9 5 7]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)


In [36]:
a_37 = np.arange(0, 5)
res_37 = np.tile(a_37, (5, 1)).astype(float)
res_37

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)


In [37]:
a_38 = range(10)
res_38 = np.fromiter(a_38, dtype=float)
res_38


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [38]:
a_39 = np.linspace(0, 1, 12, dtype=float)
a_39 = a_39[1:-1]
a_39 = np.around(a_39, decimals=3)
a_39

array([0.091, 0.182, 0.273, 0.364, 0.455, 0.545, 0.636, 0.727, 0.818,
       0.909])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [39]:
a_40 = np.random.random(n)
a_40.sort()
a_40

array([0.01498766, 0.19102744, 0.2543104 , 0.745719  , 0.75504774,
       0.75946622, 0.80418846, 0.85020436, 0.8915451 , 0.91670968])

41. How to sum a small array faster than np.sum? (★★☆)

In [43]:
%time
a_41 = np.random.random(n)
np.add.reduce(a_41)

CPU times: user 4 µs, sys: 0 ns, total: 4 µs
Wall time: 7.39 µs


6.356566222132604

42. Consider two random array A and B, check if they are equal (★★☆)

In [46]:
a_42_1 = np.random.randint(0,2,5)
a_42_2 = np.random.randint(0,2,5)
np.array_equal(a_42_1,a_42_2)

False

43. Make an array immutable (read-only) (★★☆)

44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)