<a href="https://colab.research.google.com/github/voknerog/pandas_numpy_matplotlib/blob/colab/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.21.6


3. Create a null vector of size 10 (★☆☆)

In [4]:
n = 10
a_3 = np.zeros(n)

5


array([0., 0., 0., 0., 0.])

4. How to find the memory size of any array (★☆☆)

In [7]:
res_3 = a_3.nbytes


160


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [ ]:
res_5 = [np.info(np.add), np.info(np.array)]

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [105]:
n = 10
a_6 = np.zeros(n)
a_6[4] = 1

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [106]:
n = 10
m = 49
a_7 = np.arange(n, m+1)


8. Reverse a vector (first element becomes last) (★☆☆)


In [108]:
a_8 = a_7[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [109]:
a_9 = np.arange(9)
a_9 = np.reshape(a_9, (3, 3))
a_9

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [42]:
a_10 = [1,2,0,0,4,0]
res_10 = np.nonzero(a_10)
res_10[0]


[0 1 4]


array([0, 1, 4])

11. Create a 3x3 identity matrix (★☆☆)

In [43]:
a_11 = np.identity(3)
a_11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a_12 = np.random.random((3,3,3))
a_12

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [48]:
a_13 = np.random.random((10,10))
f'min: {np.min(a_13)}, max: {np.max(a_13)}'

'min: 0.02218857906047811, max: 0.998736621823363'

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [51]:
a_14 = np.random.random(14)
a_14.mean()

0.4317770069387917

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [71]:
a_15 = np.zeros((10,10))
a_15[0] = 1
a_15[-1] = 1
a_15[:, 0] = 1
a_15[:, -1] = 1
a_15

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [78]:
a_16 = np.pad(a_15,(1,1), mode='constant')
a_16

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)<br>
0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
 0.3 == 3 * 0.1<br>

In [79]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [82]:
a_18 = np.diagflat([1, 2, 3, 4], -1)
a_18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [84]:
a_19 = np.ones((8, 8))
a_19[::2, ::2] = 0
a_19[1::2,1::2] = 0
a_19

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [101]:
a_20 = np.array((6,7,8))
res_20 = np.unravel_index(100, (6, 7, 8))
res_20

(1, 5, 4)