<a href="https://colab.research.google.com/github/voknerog/pandas_numpy_matplotlib/blob/colab/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Import the numpy package under the name np (★☆☆)

In [1]:
import numpy as np

2. Print the numpy version and the configuration (★☆☆)

In [2]:
print(np.__version__)

1.21.6


3. Create a null vector of size 10 (★☆☆)

In [3]:
n = 10
A = np.zeros(n)

4. How to find the memory size of any array (★☆☆)

In [4]:
print(A.nbytes)


80


5. How to get the documentation of the numpy add function from the command line? (★☆☆)


In [5]:
np.info(np.add)
np.info(np.array)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [6]:
n = 10
A = np.zeros(n)
A[4] = 1

7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [7]:
n = 10
m = 49
A = np.arange(n, m+1)


8. Reverse a vector (first element becomes last) (★☆☆)


In [8]:
A = A[::-1]

9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [9]:
A = np.arange(9)
A = np.reshape(A, (3, 3))
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [10]:
a_10 = [1,2,0,0,4,0]
res_10 = np.nonzero(a_10)
res_10[0]


array([0, 1, 4])

11. Create a 3x3 identity matrix (★☆☆)

In [11]:
a_11 = np.identity(3)
a_11

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

12. Create a 3x3x3 array with random values (★☆☆)

In [12]:
a_12 = np.random.random((3,3,3))
a_12

array([[[0.54880434, 0.93102314, 0.30283282],
        [0.59572449, 0.77740138, 0.36419015],
        [0.65305365, 0.81499092, 0.92364921]],

       [[0.43713931, 0.68580208, 0.65089363],
        [0.88547247, 0.29527867, 0.61208937],
        [0.98334645, 0.66564903, 0.46251476]],

       [[0.73443951, 0.92578945, 0.09269123],
        [0.60224561, 0.77901165, 0.65207166],
        [0.44136327, 0.19164109, 0.60768587]]])

13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [13]:
a_13 = np.random.random((10,10))
f'min: {np.min(a_13)}, max: {np.max(a_13)}'

'min: 0.0045084892157432055, max: 0.9879378449342937'

14. Create a random vector of size 30 and find the mean value (★☆☆)

In [14]:
a_14 = np.random.random(14)
a_14.mean()

0.5982388746112567

15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [15]:
a_15 = np.zeros((10,10))
a_15[0] = 1
a_15[-1] = 1
a_15[:, 0] = 1
a_15[:, -1] = 1
a_15

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [16]:
a_16 = np.pad(a_15,(1,1), mode='constant')
a_16

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

17. What is the result of the following expression? (★☆☆)<br>
0 * np.nan<br>
np.nan == np.nan<br>
np.inf > np.nan<br>
np.nan - np.nan<br>
np.nan in set([np.nan])<br>
 0.3 == 3 * 0.1<br>

In [17]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [18]:
a_18 = np.diagflat([1, 2, 3, 4], -1)
a_18

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [19]:
a_19 = np.ones((8, 8))
a_19[::2, ::2] = 0
a_19[1::2,1::2] = 0
a_19

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)


In [20]:
a_20 = np.array((6,7,8))
res_20 = np.unravel_index(100, (6, 7, 8))
res_20

(1, 5, 4)